export interface CategoryItem {
  title: string;
  slug: string;
  icon: string;
  description: string;
  stats: { games: string; plays: string; rating: string };
  color: string;
  searchTerm?: string;
  parentCategory?: string;
}

export const categoriesData: Record<string, CategoryItem> = {
  // Root Canonical Categories
  'action-games': {
    title: 'Action Games',
    slug: 'action-games',
    icon: '⚔️',
    description: 'Jump into the heat of the moment with our thrilling action games. Fast-paced, explosive, and intense!',
    stats: { games: '98+', plays: '4.5M+', rating: '4.8' },
    color: '#EF4444',
  },
  'adventure-games': {
    title: 'Adventure Games',
    slug: 'adventure-games',
    icon: '🗺️',
    description: 'Embark on epic journeys, explore unknown worlds, and uncover hidden treasures.',
    stats: { games: '56+', plays: '1.2M+', rating: '4.7' },
    color: '#10B981',
  },
  'arcade-games': {
    title: 'Arcade Games',
    slug: 'arcade-games',
    icon: '👾',
    description: 'Relive the golden age of gaming with classic and modern arcade experiences.',
    stats: { games: '82+', plays: '3.1M+', rating: '4.6' },
    color: '#F59E0B',
  },
  'board-games': {
    title: 'Board Games',
    slug: 'board-games',
    icon: '🎲',
    description: 'Play digital versions of your favorite classic board games with friends or AI.',
    stats: { games: '43+', plays: '890K+', rating: '4.5' },
    color: '#8B5CF6',
  },
  'puzzle-games': {
    title: 'Puzzle Games',
    slug: 'puzzle-games',
    icon: '🧩',
    description: 'Challenge your mind with our collection of the best puzzle games. Solve, match, connect, and win!',
    stats: { games: '125+', plays: '2.3M+', rating: '4.6' },
    color: '#6366F1',
  },
  'racing-games': {
    title: 'Racing Games',
    slug: 'racing-games',
    icon: '🏎️',
    description: 'Burn rubber and race to the finish line in our high-speed racing games.',
    stats: { games: '67+', plays: '5.6M+', rating: '4.7' },
    color: '#3B82F6',
  },
  'sports-games': {
    title: 'Sports Games',
    slug: 'sports-games',
    icon: '🏅',
    description: 'Compete in your favorite sports, from basketball to soccer and everything in between.',
    stats: { games: '32+', plays: '1.9M+', rating: '4.4' },
    color: '#F97316',
  },
  'strategy-games': {
    title: 'Strategy Games',
    slug: 'strategy-games',
    icon: '♟️',
    description: 'Plan your moves, build your empire, and outsmart your opponents.',
    stats: { games: '41+', plays: '2.8M+', rating: '4.8' },
    color: '#14B8A6',
  },

  // High-Volume Thematic Topic Clusters
  'car-games': {
    title: 'Car Games',
    slug: 'car-games',
    icon: '🚗',
    description: 'Get behind the wheel of supercars, trucks, and hot rods. Race, drift, park, and customize high-performance vehicles unblocked.',
    stats: { games: '1,000+', plays: '8.2M+', rating: '4.8' },
    color: '#3B82F6',
    searchTerm: 'car',
    parentCategory: 'Racing',
  },
  'zombie-games': {
    title: 'Zombie Games',
    slug: 'zombie-games',
    icon: '🧟',
    description: 'Survive the undead apocalypse! Arm yourself with weapons, build defenses, and battle waves of zombies in instant-play web games.',
    stats: { games: '330+', plays: '3.7M+', rating: '4.7' },
    color: '#10B981',
    searchTerm: 'zombie',
    parentCategory: 'Action',
  },
  'stickman-games': {
    title: 'Stickman Games',
    slug: 'stickman-games',
    icon: '🏃',
    description: 'Play the greatest stickman adventures, sniper missions, fighting duels, and parkour challenges directly in your browser.',
    stats: { games: '230+', plays: '4.1M+', rating: '4.7' },
    color: '#6366F1',
    searchTerm: 'stickman',
    parentCategory: 'Action',
  },
  '2-player-games': {
    title: '2 Player Games',
    slug: '2-player-games',
    icon: '👥',
    description: 'Grab a friend and play head-to-head on the same keyboard or online. Compete in 2-player sports, racing, and battle arenas.',
    stats: { games: '130+', plays: '2.9M+', rating: '4.8' },
    color: '#EC4899',
    searchTerm: '2 player',
    parentCategory: 'Arcade',
  },
  'escape-games': {
    title: 'Escape Games',
    slug: 'escape-games',
    icon: '🗝️',
    description: 'Solve intricate room riddles, find hidden clues, crack locks, and escape tricky chambers in thrilling mystery room games.',
    stats: { games: '530+', plays: '3.4M+', rating: '4.6' },
    color: '#F59E0B',
    searchTerm: 'escape',
    parentCategory: 'Puzzle',
  },
  'shooting-games': {
    title: 'Shooting Games',
    slug: 'shooting-games',
    icon: '🎯',
    description: 'Aim down sights in FPS shooters, tactical sniper missions, and target practice arcade games. Fast reflex action unblocked.',
    stats: { games: '580+', plays: '6.3M+', rating: '4.8' },
    color: '#EF4444',
    searchTerm: 'shoot',
    parentCategory: 'Action',
  },
  'drift-games': {
    title: 'Drift Games',
    slug: 'drift-games',
    icon: '🏎️',
    description: 'Slide around sharp corners, burn tires on asphalt tracks, and score monster drift points in realistic 3D car drift simulators.',
    stats: { games: '110+', plays: '2.1M+', rating: '4.7' },
    color: '#8B5CF6',
    searchTerm: 'drift',
    parentCategory: 'Racing',
  },
  'moto-games': {
    title: 'Moto Games',
    slug: 'moto-games',
    icon: '🏍️',
    description: 'Stunt across dirt hills, conquer obstacle courses, and speed through highway traffic on motorcycles and BMX bikes.',
    stats: { games: '125+', plays: '2.5M+', rating: '4.6' },
    color: '#F97316',
    searchTerm: 'moto',
    parentCategory: 'Racing',
  },
  'dress-up-games': {
    title: 'Dress Up Games',
    slug: 'dress-up-games',
    icon: '👗',
    description: 'Showcase your fashion style! Style models, design stunning outfits, choose makeup, and create dream looks in free makeover games.',
    stats: { games: '350+', plays: '4.8M+', rating: '4.7' },
    color: '#EC4899',
    searchTerm: 'dress',
    parentCategory: 'Arcade',
  },
  'cooking-games': {
    title: 'Cooking Games',
    slug: 'cooking-games',
    icon: '🍳',
    description: 'Bake cakes, manage busy restaurants, prepare sushi, and become a master chef in delicious cooking simulation games.',
    stats: { games: '120+', plays: '2.2M+', rating: '4.6' },
    color: '#F59E0B',
    searchTerm: 'cook',
    parentCategory: 'Arcade',
  },
  'football-games': {
    title: 'Football Games',
    slug: 'football-games',
    icon: '⚽',
    description: 'Score sensational goals, take penalty shootouts, and lead your soccer club to world championship victory.',
    stats: { games: '120+', plays: '3.1M+', rating: '4.7' },
    color: '#10B981',
    searchTerm: 'football',
    parentCategory: 'Sports',
  },
  'basketball-games': {
    title: 'Basketball Games',
    slug: 'basketball-games',
    icon: '🏀',
    description: 'Sink three-pointers, throw down monster dunks, and win high-stakes court shootouts in free online basketball games.',
    stats: { games: '100+', plays: '2.4M+', rating: '4.6' },
    color: '#EA580C',
    searchTerm: 'basket',
    parentCategory: 'Sports',
  },
  'clicker-games': {
    title: 'Clicker Games',
    slug: 'clicker-games',
    icon: '👆',
    description: 'Tap your way to billions! Upgrade multipliers, unlock automated generators, and watch your empire scale in idle clicker games.',
    stats: { games: '130+', plays: '1.8M+', rating: '4.5' },
    color: '#06B6D4',
    searchTerm: 'clicker',
    parentCategory: 'Strategy',
  },
  'runner-games': {
    title: 'Runner Games',
    slug: 'runner-games',
    icon: '🏃‍♂️',
    description: 'Dodge obstacles, jump over perils, slide under barriers, and collect coins in adrenaline-pumping endless runner games.',
    stats: { games: '670+', plays: '7.2M+', rating: '4.8' },
    color: '#3B82F6',
    searchTerm: 'runner',
    parentCategory: 'Arcade',
  },
  'ninja-games': {
    title: 'Ninja Games',
    slug: 'ninja-games',
    icon: '🥷',
    description: 'Stealth through shadows, slice fruit and enemies with katanas, and master ancient martial arts in free ninja games.',
    stats: { games: '85+', plays: '1.4M+', rating: '4.6' },
    color: '#334155',
    searchTerm: 'ninja',
    parentCategory: 'Action',
  },
  'chess-games': {
    title: 'Chess Games',
    slug: 'chess-games',
    icon: '♟️',
    description: 'Master grandmaster tactics, solve chess checkmate puzzles, and play against intelligent chess bots at all skill levels.',
    stats: { games: '40+', plays: '950K+', rating: '4.8' },
    color: '#64748B',
    searchTerm: 'chess',
    parentCategory: 'Board',
  },
  'mahjong-games': {
    title: 'Mahjong Games',
    slug: 'mahjong-games',
    icon: '🀄',
    description: 'Match traditional Chinese tiles, clear multi-layered pyramids, and relax with classic Solitaire Mahjong boards.',
    stats: { games: '50+', plays: '1.6M+', rating: '4.7' },
    color: '#0D9488',
    searchTerm: 'mahjong',
    parentCategory: 'Board',
  },
  'solitaire-games': {
    title: 'Solitaire Games',
    slug: 'solitaire-games',
    icon: '🃏',
    description: 'Play Klondike, Spider, FreeCell, and Pyramid Solitaire online with smooth card animations and hints.',
    stats: { games: '60+', plays: '2.0M+', rating: '4.7' },
    color: '#4F46E5',
    searchTerm: 'solitaire',
    parentCategory: 'Board',
  },
  'unblocked-games': {
    title: 'Unblocked Games',
    slug: 'unblocked-games',
    icon: '🔓',
    description: 'Play unblocked games for school or work with zero download. Fast, safe HTML5 games that run on Chromebooks and mobile browsers.',
    stats: { games: '17,000+', plays: '15M+', rating: '4.9' },
    color: '#10B981',
    searchTerm: '',
    parentCategory: 'Arcade',
  },
  'brain-games': {
    title: 'Brain Games',
    slug: 'brain-games',
    icon: '🧠',
    description: 'Sharpen your memory, IQ, and mental reflexes with logic puzzles, number grids, and brain teaser challenges.',
    stats: { games: '300+', plays: '4.2M+', rating: '4.8' },
    color: '#A855F7',
    searchTerm: 'brain',
    parentCategory: 'Puzzle',
  },
  'multiplayer-games': {
    title: 'Multiplayer Games',
    slug: 'multiplayer-games',
    icon: '🌐',
    description: 'Challenge players around the globe in real-time online multiplayer battles, arenas, and sports tourneys.',
    stats: { games: '200+', plays: '5.1M+', rating: '4.8' },
    color: '#0284C7',
    searchTerm: 'multiplayer',
    parentCategory: 'Action',
  },

  // High-Volume Programmatic Topic Clusters (Rankings Expansion)
  'unblocked-games-76': {
    title: 'Unblocked Games 76',
    slug: 'unblocked-games-76',
    icon: '🚀',
    description: 'Play Unblocked Games 76 online for free directly in your web browser. Safe, fast-loading HTML5 games unblocked for school Chromebooks with zero restrictions.',
    stats: { games: '15,000+', plays: '12M+', rating: '4.9' },
    color: '#10B981',
    searchTerm: '',
    parentCategory: 'Arcade',
  },
  'unblocked-games-66': {
    title: 'Unblocked Games 66 EZ',
    slug: 'unblocked-games-66',
    icon: '⚡',
    description: 'Access Unblocked Games 66 EZ for free instantly. Play the most popular browser games at school or work on any PC, Chromebook, or mobile device.',
    stats: { games: '14,000+', plays: '10M+', rating: '4.9' },
    color: '#6366F1',
    searchTerm: '',
    parentCategory: 'Arcade',
  },
  'chromebook-games': {
    title: 'Chromebook Games',
    slug: 'chromebook-games',
    icon: '💻',
    description: 'Lightweight, ultra-fast browser games specifically optimized for Google Chromebooks. Zero download, no installation, runs at 60 FPS on ChromeOS.',
    stats: { games: '12,000+', plays: '9.4M+', rating: '4.8' },
    color: '#3B82F6',
    searchTerm: '',
    parentCategory: 'Arcade',
  },
  'games-for-school': {
    title: 'Games for School',
    slug: 'games-for-school',
    icon: '🏫',
    description: 'Safe, fun, and unblocked online games to play at school during study hall or break time. No downloads, no blocked proxies, just instant web fun.',
    stats: { games: '11,000+', plays: '8.7M+', rating: '4.8' },
    color: '#F59E0B',
    searchTerm: '',
    parentCategory: 'Arcade',
  },
  'no-download-games': {
    title: 'No Download Games',
    slug: 'no-download-games',
    icon: '⚡',
    description: 'Instant play games with 0 download required. Click and play thousands of high-speed HTML5 and WebGL games directly on desktop or mobile.',
    stats: { games: '17,000+', plays: '16M+', rating: '4.9' },
    color: '#EC4899',
    searchTerm: '',
    parentCategory: 'Arcade',
  },
  'sniper-games': {
    title: 'Sniper Games',
    slug: 'sniper-games',
    icon: '🎯',
    description: 'Take aim through long-range rifle scopes in tactical sniper shooter games. Steady your breath, adjust for distance, and eliminate targets with precision.',
    stats: { games: '240+', plays: '3.8M+', rating: '4.7' },
    color: '#EF4444',
    searchTerm: 'sniper',
    parentCategory: 'Action',
  },
  'fps-games': {
    title: 'FPS Games',
    slug: 'fps-games',
    icon: '🔫',
    description: 'First-person shooter games in your web browser. Experience intense tactical combat, counter-terrorist operations, and deathmatch multiplayer arenas.',
    stats: { games: '310+', plays: '5.4M+', rating: '4.8' },
    color: '#DC2626',
    searchTerm: 'fps',
    parentCategory: 'Action',
  },
  'police-car-games': {
    title: 'Police Car Games',
    slug: 'police-car-games',
    icon: '🚓',
    description: 'Turn on police sirens and chase down fugitives in high-speed cop car pursuits, patrol missions, and tactical interception challenges.',
    stats: { games: '180+', plays: '2.9M+', rating: '4.7' },
    color: '#2563EB',
    searchTerm: 'police',
    parentCategory: 'Racing',
  },
  'truck-games': {
    title: 'Truck Simulator Games',
    slug: 'truck-games',
    icon: '🚛',
    description: 'Drive massive 18-wheelers, monster trucks, and heavy cargo rigs. Navigate rugged mountain passes, highway delivery routes, and extreme terrain.',
    stats: { games: '210+', plays: '3.6M+', rating: '4.7' },
    color: '#D97706',
    searchTerm: 'truck',
    parentCategory: 'Racing',
  },
  'bus-games': {
    title: 'Bus Simulator Games',
    slug: 'bus-games',
    icon: '🚌',
    description: 'Sit in the driver seat of city transit buses, coach liners, and school buses. Pick up passengers, follow timetables, and park safely.',
    stats: { games: '140+', plays: '2.1M+', rating: '4.6' },
    color: '#059669',
    searchTerm: 'bus',
    parentCategory: 'Racing',
  },
  'airplane-games': {
    title: 'Airplane & Flight Games',
    slug: 'airplane-games',
    icon: '✈️',
    description: 'Soar through the skies in commercial jet airliners, fighter jets, and acrobatic stunt planes. Take off, dogfight, and land smoothly in realistic flight games.',
    stats: { games: '160+', plays: '2.7M+', rating: '4.7' },
    color: '#0284C7',
    searchTerm: 'plane',
    parentCategory: 'Action',
  },
  'boat-games': {
    title: 'Boat & Jet Ski Games',
    slug: 'boat-games',
    icon: '🚤',
    description: 'Race across ocean waves, speed through tropical canals, and pilot high-performance speedboats and jet skis in watercraft racing simulators.',
    stats: { games: '95+', plays: '1.5M+', rating: '4.6' },
    color: '#0EA5E9',
    searchTerm: 'boat',
    parentCategory: 'Racing',
  },
  'tank-games': {
    title: 'Tank War Games',
    slug: 'tank-games',
    icon: '🛡️',
    description: 'Command armored tanks, fire heavy cannons, and conquer battlefield arenas in explosive World War and futuristic tank combat simulations.',
    stats: { games: '175+', plays: '3.2M+', rating: '4.7' },
    color: '#4B5563',
    searchTerm: 'tank',
    parentCategory: 'Action',
  },
  'war-games': {
    title: 'War & Military Games',
    slug: 'war-games',
    icon: '⚔️',
    description: 'Lead armies, manage frontline logistics, and defeat hostile coalitions in epic tactical military strategy and combat war games.',
    stats: { games: '260+', plays: '4.4M+', rating: '4.8' },
    color: '#991B1B',
    searchTerm: 'war',
    parentCategory: 'Strategy',
  },
  'horror-games': {
    title: 'Horror & Scary Games',
    slug: 'horror-games',
    icon: '👻',
    description: 'Survive creepy haunted houses, eerie jump scares, and spine-chilling monster chases in thrilling free online horror and escape games.',
    stats: { games: '190+', plays: '3.5M+', rating: '4.7' },
    color: '#4C1D95',
    searchTerm: 'horror',
    parentCategory: 'Action',
  },
  'parkour-games': {
    title: 'Parkour & Freerun Games',
    slug: 'parkour-games',
    icon: '🏃',
    description: 'Leap across rooftop skylines, vault over city barriers, and scale towering walls in gravity-defying free running parkour simulators.',
    stats: { games: '170+', plays: '3.1M+', rating: '4.8' },
    color: '#0D9488',
    searchTerm: 'parkour',
    parentCategory: 'Action',
  },
  'sword-games': {
    title: 'Sword & Fighting Games',
    slug: 'sword-games',
    icon: '🗡️',
    description: 'Clash blades with medieval knights, samurai warriors, and gladiator champions in visceral martial arts and sword fighting duels.',
    stats: { games: '150+', plays: '2.6M+', rating: '4.7' },
    color: '#B91C1C',
    searchTerm: 'fight',
    parentCategory: 'Action',
  },
  'match-3-games': {
    title: 'Match 3 Games',
    slug: 'match-3-games',
    icon: '💎',
    description: 'Swap, align, and pop colorful jewels, candies, and crystals in addictive matching puzzle games packed with rewarding booster combos.',
    stats: { games: '380+', plays: '5.8M+', rating: '4.8' },
    color: '#9333EA',
    searchTerm: 'match',
    parentCategory: 'Puzzle',
  },
  'hidden-object-games': {
    title: 'Hidden Object Games',
    slug: 'hidden-object-games',
    icon: '🔍',
    description: 'Test your observation skills by scouring detailed illustrated scenes for disguised relics, secret clues, and mystery items.',
    stats: { games: '140+', plays: '2.0M+', rating: '4.6' },
    color: '#D97706',
    searchTerm: 'hidden',
    parentCategory: 'Puzzle',
  },
  'bubble-shooter-games': {
    title: 'Bubble Shooter Games',
    slug: 'bubble-shooter-games',
    icon: '🫧',
    description: 'Aim your cannon, match three or more bubbles of the same color, and clear the screen before the ceiling drops in classic bubble shooters.',
    stats: { games: '210+', plays: '4.3M+', rating: '4.7' },
    color: '#06B6D4',
    searchTerm: 'bubble',
    parentCategory: 'Puzzle',
  },
  'jigsaw-puzzle-games': {
    title: 'Jigsaw Puzzle Games',
    slug: 'jigsaw-puzzle-games',
    icon: '🧩',
    description: 'Piece together stunning photographic landscapes, animals, and artwork with peaceful digital jigsaw puzzles at various difficulty levels.',
    stats: { games: '120+', plays: '1.7M+', rating: '4.6' },
    color: '#4F46E5',
    searchTerm: 'jigsaw',
    parentCategory: 'Puzzle',
  },
  'word-games': {
    title: 'Word & Crossword Games',
    slug: 'word-games',
    icon: '📝',
    description: 'Expand your vocabulary, solve anagrams, crack crosswords, and connect letters in mentally stimulating word search games.',
    stats: { games: '160+', plays: '2.8M+', rating: '4.7' },
    color: '#16A34A',
    searchTerm: 'word',
    parentCategory: 'Puzzle',
  },
  'typing-games': {
    title: 'Typing & Speed Games',
    slug: 'typing-games',
    icon: '⌨️',
    description: 'Boost your typing speed and words-per-minute accuracy while destroying asteroids, defending kingdoms, and racing cars in fast typing games.',
    stats: { games: '80+', plays: '1.2M+', rating: '4.7' },
    color: '#6366F1',
    searchTerm: 'typing',
    parentCategory: 'Puzzle',
  },
  'io-games': {
    title: '.io Games',
    slug: 'io-games',
    icon: '🕹️',
    description: 'Jump into massive multiplayer battle-royale arenas, consume smaller orbs, grow your avatar, and survive against real players worldwide in top .io games.',
    stats: { games: '290+', plays: '7.6M+', rating: '4.8' },
    color: '#E11D48',
    searchTerm: 'io',
    parentCategory: 'Arcade',
  },
  '3-player-games': {
    title: '3 Player Games',
    slug: '3-player-games',
    icon: '👥',
    description: 'Gather three friends on one screen or keyboard! Play 3-player party mini-games, racing tournaments, and battle royale brawlers.',
    stats: { games: '90+', plays: '1.4M+', rating: '4.7' },
    color: '#F43F5E',
    searchTerm: '3 player',
    parentCategory: 'Arcade',
  },
  '4-player-games': {
    title: '4 Player Games',
    slug: '4-player-games',
    icon: '🎮',
    description: 'The ultimate 4-player couch party experience. Compete in 4-way races, fighting tournaments, and team showdowns on a single device.',
    stats: { games: '110+', plays: '1.9M+', rating: '4.8' },
    color: '#EC4899',
    searchTerm: '4 player',
    parentCategory: 'Arcade',
  },
  'pool-games': {
    title: '8 Ball Pool Games',
    slug: 'pool-games',
    icon: '🎱',
    description: 'Chalk your cue stick, calculate angle rebounds, and pot stripes and solids in realistic 8-ball and 9-ball billiard simulation games.',
    stats: { games: '85+', plays: '2.3M+', rating: '4.7' },
    color: '#1E293B',
    searchTerm: 'pool',
    parentCategory: 'Sports',
  },
  'cricket-games': {
    title: 'Cricket Games',
    slug: 'cricket-games',
    icon: '🏏',
    description: 'Step up to the batting crease, hit massive sixes, and bowl out rivals in high-stakes T20 and World Cup cricket championship games.',
    stats: { games: '90+', plays: '2.1M+', rating: '4.6' },
    color: '#15803D',
    searchTerm: 'cricket',
    parentCategory: 'Sports',
  },
  'tennis-games': {
    title: 'Tennis Games',
    slug: 'tennis-games',
    icon: '🎾',
    description: 'Serve aces, volley across clay and grass courts, and win Grand Slam championship matches in fast-paced racket sports simulators.',
    stats: { games: '80+', plays: '1.6M+', rating: '4.6' },
    color: '#84CC16',
    searchTerm: 'tennis',
    parentCategory: 'Sports',
  },
  'golf-games': {
    title: 'Mini Golf Games',
    slug: 'golf-games',
    icon: '⛳',
    description: 'Sink tricky putts across windmills, loop-de-loops, and multi-tier greens in relaxing and competitive miniature golf arcade games.',
    stats: { games: '95+', plays: '1.8M+', rating: '4.6' },
    color: '#10B981',
    searchTerm: 'golf',
    parentCategory: 'Sports',
  },
  'boxing-games': {
    title: 'Boxing & Fighting Games',
    slug: 'boxing-games',
    icon: '🥊',
    description: 'Throw jabs, hooks, and knock-out uppercuts in the boxing ring. Dodge opponent swings and claim the heavyweight world champion belt.',
    stats: { games: '115+', plays: '2.4M+', rating: '4.7' },
    color: '#B91C1C',
    searchTerm: 'boxing',
    parentCategory: 'Sports',
  },
  'bowling-games': {
    title: 'Bowling Games',
    slug: 'bowling-games',
    icon: '🎳',
    description: 'Spin the bowling ball down polished hardwood lanes, adjust spin curves, and knock down strikes and spares in classic ten-pin bowling games.',
    stats: { games: '75+', plays: '1.3M+', rating: '4.5' },
    color: '#475569',
    searchTerm: 'bowling',
    parentCategory: 'Sports',
  },
  'retro-arcade-games': {
    title: 'Retro Arcade Games',
    slug: 'retro-arcade-games',
    icon: '👾',
    description: 'Play timeless 8-bit and 16-bit classics inspired by 1980s and 1990s arcade machines. Pixel-perfect retro platformers, space invaders, and maze games.',
    stats: { games: '340+', plays: '4.9M+', rating: '4.8' },
    color: '#A855F7',
    searchTerm: 'retro',
    parentCategory: 'Arcade',
  },
  'physics-games': {
    title: 'Physics & Ragdoll Games',
    slug: 'physics-games',
    icon: '⚙️',
    description: 'Experiment with gravity, momentum, structural balance, and hilarious ragdoll physics in interactive sandbox puzzle games.',
    stats: { games: '220+', plays: '3.7M+', rating: '4.7' },
    color: '#0891B2',
    searchTerm: 'physics',
    parentCategory: 'Puzzle',
  },
  'casual-games': {
    title: 'Casual & Relaxing Games',
    slug: 'casual-games',
    icon: '☕',
    description: 'Unwind and de-stress with easy, accessible, low-pressure games designed for pure relaxation and quick gameplay breaks.',
    stats: { games: '540+', plays: '6.2M+', rating: '4.8' },
    color: '#F59E0B',
    searchTerm: 'casual',
    parentCategory: 'Arcade',
  },
  'tower-defense-games': {
    title: 'Tower Defense Games',
    slug: 'tower-defense-games',
    icon: '🏰',
    description: 'Build turret fortresses, upgrade cannon towers, and strategically repel waves of encroaching invaders in top tower defense tactical games.',
    stats: { games: '180+', plays: '3.9M+', rating: '4.8' },
    color: '#7C3AED',
    searchTerm: 'defense',
    parentCategory: 'Strategy',
  },
};

export type CategoryData = CategoryItem;
