export const runtime = 'edge';
import React from 'react';
import Link from 'next/link';
import { Gamepad2, Sparkles, TrendingUp, Code2, Users, ArrowRight, LogIn } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';
import StudioSidebar from '@/components/developer/StudioSidebar';

export const metadata = {
  title: 'Developer Studio - Spielcade',
  description: 'Manage, submit, and monetize your browser games.',
  robots: {
    index: false,
    follow: false,
  },
};

export default async function StudioLayout({ children }: { children: React.ReactNode }) {
  const supabase = createClient();
  const { data: authData } = await supabase.auth.getUser();
  const user = authData?.user || null;

  // If unauthenticated, show the inviting Developer Studio Onboarding Gateway
  if (!user) {
    return (
      <div className="min-h-screen bg-gray-50 dark:bg-[#05050F] pt-28 pb-16 transition-colors text-gray-900 dark:text-white flex items-center justify-center">
        <div className="container mx-auto px-4 max-w-3xl">
          <div className="bg-white dark:bg-[#111228] rounded-3xl border border-gray-200 dark:border-white/10 shadow-2xl overflow-hidden p-8 sm:p-12 text-center">
            
            <div className="w-16 h-16 rounded-2xl bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 flex items-center justify-center mx-auto mb-6 shadow-inner">
              <Gamepad2 size={36} />
            </div>

            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-200 dark:border-indigo-500/20 text-indigo-600 dark:text-indigo-400 text-xs font-bold uppercase tracking-wider mb-4">
              <Sparkles size={13} /> Creator Ecosystem
            </div>

            <h1 className="text-3xl sm:text-4xl font-black font-outfit text-gray-900 dark:text-white tracking-tight mb-4">
              Welcome to Spielcade Developer Studio
            </h1>

            <p className="text-sm sm:text-base text-gray-600 dark:text-gray-300 max-w-xl mx-auto mb-8 leading-relaxed">
              Sign in to manage your submissions, access the interactive SDK simulator, generate API keys, and monetize your HTML5 & WebGL titles with 70% net revenue share.
            </p>

            {/* Feature highlights grid */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8 text-left">
              <div className="p-4 rounded-2xl bg-gray-50 dark:bg-black/20 border border-gray-200 dark:border-white/5">
                <TrendingUp className="text-emerald-500 mb-2" size={20} />
                <h3 className="text-xs font-bold text-gray-900 dark:text-white">70% Net Revenue</h3>
                <p className="text-[11px] text-gray-500 mt-1">Keep 70% of all ad impressions generated by your games.</p>
              </div>

              <div className="p-4 rounded-2xl bg-gray-50 dark:bg-black/20 border border-gray-200 dark:border-white/5">
                <Code2 className="text-indigo-500 mb-2" size={20} />
                <h3 className="text-xs font-bold text-gray-900 dark:text-white">Instant SDK</h3>
                <p className="text-[11px] text-gray-500 mt-1">Plug-and-play leaderboards, scores, and achievement toasts.</p>
              </div>

              <div className="p-4 rounded-2xl bg-gray-50 dark:bg-black/20 border border-gray-200 dark:border-white/5">
                <Users className="text-blue-500 mb-2" size={20} />
                <h3 className="text-xs font-bold text-gray-900 dark:text-white">Global Distribution</h3>
                <p className="text-[11px] text-gray-500 mt-1">Reach thousands of active browser gaming players instantly.</p>
              </div>
            </div>

            {/* Actions */}
            <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
              <Link
                href="/login?next=/studio"
                className="w-full sm:w-auto px-8 py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white rounded-2xl font-bold text-sm flex items-center justify-center gap-2 shadow-lg shadow-indigo-600/30 transition-all hover:scale-105 active:scale-95"
              >
                <LogIn size={16} /> Sign In to Launch Studio
              </Link>
              <Link
                href="/developers"
                className="w-full sm:w-auto px-6 py-3.5 bg-gray-100 hover:bg-gray-200 dark:bg-white/5 dark:hover:bg-white/10 text-gray-800 dark:text-gray-200 rounded-2xl font-bold text-sm flex items-center justify-center gap-2 transition-all"
              >
                Learn More on Developers Hub <ArrowRight size={15} />
              </Link>
            </div>

          </div>
        </div>
      </div>
    );
  }

  // Check admin role
  let isAdmin = false;
  const { data: profile } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .maybeSingle();

  if (profile?.role === 'admin') {
    isAdmin = true;
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-[#05050F] pt-24 pb-12 transition-colors text-gray-900 dark:text-white">
      <div className="container mx-auto px-4 md:px-6 lg:px-8 max-w-7xl">
        
        <div className="mb-8 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-extrabold font-outfit tracking-wide flex items-center gap-3">
              <Gamepad2 className="text-[#6366F1]" size={32} />
              Developer Studio
            </h1>
            <p className="text-gray-500 dark:text-gray-400 mt-1 text-sm">
              Publish games, test SDK events, monitor revenue, and manage platform credentials.
            </p>
          </div>

          <Link
            href="/developers"
            className="inline-flex items-center gap-1 text-xs font-bold text-indigo-600 dark:text-indigo-400 hover:underline"
          >
            Visit Public Developer Portal →
          </Link>
        </div>

        <div className="flex flex-col lg:flex-row gap-8">
          
          {/* Adaptive Client Sidebar */}
          <StudioSidebar isAdmin={isAdmin} />

          {/* Main Content Area */}
          <main className="flex-1 min-w-0">
            {children}
          </main>

        </div>
      </div>
    </div>
  );
}
