import { Metadata } from 'next';
import Link from 'next/link';
import { Search, MessageCircle, Gamepad2, UserCircle, ShieldQuestion } from 'lucide-react';
import HelpAccordion from '@/components/HelpAccordion';

export const runtime = 'edge';


export const metadata: Metadata = {
  title: 'Help Center & FAQ | Spielcade',
  description: 'Find answers to common questions about Spielcade, including account management, gameplay issues, developer publishing, and more.',
  alternates: {
    canonical: 'https://spielcade.com/help',
  },
  openGraph: {
    title: 'Help Center | Spielcade',
    description: 'Find answers to your questions and learn how to get the most out of Spielcade.',
    url: 'https://spielcade.com/help',
    siteName: 'Spielcade',
    locale: 'en_US',
    type: 'website',
  },
};

export default function HelpCenter() {
  const accountFaqs = [
    {
      question: "How do I create an account?",
      answer: "Click the 'Login' button in the top right corner of the screen, and select 'Sign up'. You can create an account using your email address, or securely sign in using your Google or GitHub account."
    },
    {
      question: "How do I reset my password?",
      answer: "Go to the Login page and click on 'Forgot Password?'. Enter your email address, and we will send you a secure link to reset your password."
    },
    {
      question: "Is my game progress saved automatically?",
      answer: "Yes! As long as you are logged into your Spielcade account, your progress, achievements, and high scores for supported games are automatically saved to the cloud."
    },
    {
      question: "How do I delete my account?",
      answer: "You can delete your account by navigating to your Profile Settings, clicking on the 'Security' tab, and selecting 'Delete Account'. Please note that this action is irreversible and all your game data will be lost."
    }
  ];

  const gameplayFaqs = [
    {
      question: "Do I need to download anything to play?",
      answer: "No! All games on Spielcade run directly in your web browser. There are no downloads, installations, or plugins required."
    },
    {
      question: "Why is a game running slowly or lagging?",
      answer: "Lag can be caused by a slow internet connection or hardware limitations. Try closing other browser tabs, ensuring hardware acceleration is enabled in your browser settings, or switching to a different browser like Chrome or Edge."
    },
    {
      question: "Can I play on my phone or tablet?",
      answer: "Yes, many of our games are fully optimized for mobile devices with touch controls. Games that require a keyboard and mouse will have a desktop-only indicator on their preview cards."
    },
    {
      question: "How do I earn Achievements?",
      answer: "Certain games feature integrated Spielcade Achievements. When you complete specific challenges in those games while logged in, the achievements will automatically unlock and appear on your public profile."
    }
  ];

  const developerFaqs = [
    {
      question: "How can I publish my game on Spielcade?",
      answer: (
        <>
          We are always looking for great new games! You can submit your HTML5 or WebGL game for review by navigating to our <Link href="/developers" className="text-[#6366F1] hover:underline">Developers portal</Link>.
        </>
      )
    },
    {
      question: "What formats do you support?",
      answer: "We primarily support HTML5 games (Canvas/WebGL) built with engines like Unity, Godot, Construct 3, Phaser, and GameMaker Studio."
    },
    {
      question: "Do developers earn money?",
      answer: "Yes! We offer a revenue-sharing model based on the ad impressions generated by your game. Verified developers get access to a dedicated dashboard to track their earnings and analytics."
    }
  ];

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-[#05050F] pb-24 transition-colors">
      
      {/* Hero Section */}
      <div className="bg-[#6366F1] dark:bg-[#0A0A1B] text-white pt-24 pb-20 px-4 relative overflow-hidden border-b border-[#6366F1]/20">
        <div className="absolute inset-0 bg-[url('/noise.png')] opacity-10 mix-blend-overlay pointer-events-none"></div>
        <div className="absolute -top-40 -right-40 w-96 h-96 bg-white/10 rounded-full blur-3xl pointer-events-none"></div>
        
        <div className="container mx-auto max-w-3xl text-center relative z-10">
          <h1 className="text-4xl md:text-6xl font-black font-outfit mb-6">
            How can we help you?
          </h1>
          <p className="text-lg md:text-xl text-white/80 mb-8 max-w-2xl mx-auto">
            Search our knowledge base or browse the categories below to find answers to your questions.
          </p>
          
          {/* Search Bar */}
          <div className="relative max-w-2xl mx-auto">
            <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-6 h-6 text-gray-400" />
            <input 
              type="text" 
              placeholder="Search for answers (e.g., 'Reset password')" 
              className="w-full bg-white text-gray-900 rounded-2xl py-4 pl-14 pr-6 text-lg shadow-xl focus:outline-none focus:ring-4 focus:ring-white/30 transition-all placeholder:text-gray-400"
            />
            <button className="absolute right-2 top-1/2 -translate-y-1/2 bg-[#6366F1] hover:bg-[#5457DF] text-white px-6 py-2 rounded-xl font-bold transition-colors">
              Search
            </button>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 md:px-6 max-w-5xl -mt-8 relative z-20">
        
        {/* Quick Links Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16">
          <div className="bg-white dark:bg-[#111228] p-6 rounded-2xl shadow-lg border border-gray-100 dark:border-white/5 flex flex-col items-center text-center hover:-translate-y-1 transition-transform">
            <div className="w-16 h-16 rounded-full bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center text-blue-600 dark:text-blue-400 mb-4">
              <UserCircle size={32} />
            </div>
            <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">My Account</h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm">Manage your profile, password, and privacy settings.</p>
          </div>
          
          <div className="bg-white dark:bg-[#111228] p-6 rounded-2xl shadow-lg border border-gray-100 dark:border-white/5 flex flex-col items-center text-center hover:-translate-y-1 transition-transform">
            <div className="w-16 h-16 rounded-full bg-green-100 dark:bg-green-900/30 flex items-center justify-center text-green-600 dark:text-green-400 mb-4">
              <Gamepad2 size={32} />
            </div>
            <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">Gameplay</h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm">Troubleshoot lag, saves, and achievement issues.</p>
          </div>

          <div className="bg-white dark:bg-[#111228] p-6 rounded-2xl shadow-lg border border-gray-100 dark:border-white/5 flex flex-col items-center text-center hover:-translate-y-1 transition-transform">
            <div className="w-16 h-16 rounded-full bg-purple-100 dark:bg-purple-900/30 flex items-center justify-center text-purple-600 dark:text-purple-400 mb-4">
              <ShieldQuestion size={32} />
            </div>
            <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-2">Trust & Safety</h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm">Report users, understand bans, and read our policies.</p>
          </div>
        </div>

        {/* FAQ Sections */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
          
          <div className="lg:col-span-8 space-y-12">
            <section id="account">
              <div className="flex items-center gap-3 mb-6">
                <UserCircle className="w-8 h-8 text-[#6366F1]" />
                <h2 className="text-3xl font-bold font-outfit text-gray-900 dark:text-white">Account & Profile</h2>
              </div>
              <HelpAccordion faqs={accountFaqs} />
            </section>

            <section id="gameplay">
              <div className="flex items-center gap-3 mb-6">
                <Gamepad2 className="w-8 h-8 text-[#10B981]" />
                <h2 className="text-3xl font-bold font-outfit text-gray-900 dark:text-white">Playing Games</h2>
              </div>
              <HelpAccordion faqs={gameplayFaqs} />
            </section>

            <section id="developers">
              <div className="flex items-center gap-3 mb-6">
                <ShieldQuestion className="w-8 h-8 text-[#F59E0B]" />
                <h2 className="text-3xl font-bold font-outfit text-gray-900 dark:text-white">For Developers</h2>
              </div>
              <HelpAccordion faqs={developerFaqs} />
            </section>
          </div>

          {/* Sticky Sidebar */}
          <div className="lg:col-span-4">
            <div className="sticky top-24">
              <div className="bg-gradient-to-br from-[#6366F1] to-[#8B5CF6] rounded-3xl p-8 text-white text-center shadow-xl">
                <div className="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center mx-auto mb-6 backdrop-blur-sm">
                  <MessageCircle size={32} />
                </div>
                <h3 className="text-2xl font-bold font-outfit mb-3">Still need help?</h3>
                <p className="text-white/80 mb-8">
                  Can't find the answer you're looking for? Our support team is here to assist you.
                </p>
                <Link 
                  href="/contact" 
                  className="inline-block w-full bg-white text-[#6366F1] font-bold py-4 rounded-xl hover:bg-gray-50 transition-colors shadow-lg"
                >
                  Contact Support
                </Link>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
